/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

package sub



import _ "runtime/cgo"
import "unsafe"

type _ unsafe.Pointer



type _swig_fnptr *byte
type _swig_memberptr *byte

//extern subSwigCgocall
func SwigCgocall()
//extern subSwigCgocallDone
func SwigCgocallDone()
//extern subSwigCgocallBack
func SwigCgocallBack()
//extern subSwigCgocallBackDone
func SwigCgocallBackDone()

type SwigcptrSub uintptr

func (p SwigcptrSub) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrSub) SwigIsSub() {
}

func _swig_wrap_new_sub() SwigcptrSub

func NewSub() Sub {
	return _swig_wrap_new_sub()
}

func _swig_wrap_sub_Init(SwigcptrSub, int, *string)

func (arg1 SwigcptrSub) Init(arg2 int, arg3 *string) {
	_swig_wrap_sub_Init(arg1, arg2, arg3)
}

func _swig_wrap_delete_sub(uintptr)

func DeleteSub(arg1 Sub) {
	_swig_wrap_delete_sub(arg1.Swigcptr())
}

type Sub interface {
	Swigcptr() uintptr
	SwigIsSub()
	Init(arg2 int, arg3 *string)
}


type SwigcptrVoid uintptr
type Void interface {
	Swigcptr() uintptr;
}
func (p SwigcptrVoid) Swigcptr() uintptr {
	return uintptr(p)
}

