// Code generated by protoc-gen-go.
// source: message.proto
// DO NOT EDIT!

/*
Package delta is a generated protocol buffer package.

It is generated from these files:
	message.proto

It has these top-level messages:
	Message
	Point
*/
package delta

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type Message_Type int32

const (
	Message_ERROR Message_Type = 1
	Message_START Message_Type = 2
	Message_STOP  Message_Type = 3
	Message_PING  Message_Type = 4
	Message_POINT Message_Type = 5
)

var Message_Type_name = map[int32]string{
	1: "ERROR",
	2: "START",
	3: "STOP",
	4: "PING",
	5: "POINT",
}
var Message_Type_value = map[string]int32{
	"ERROR": 1,
	"START": 2,
	"STOP":  3,
	"PING":  4,
	"POINT": 5,
}

func (x Message_Type) Enum() *Message_Type {
	p := new(Message_Type)
	*p = x
	return p
}
func (x Message_Type) String() string {
	return proto.EnumName(Message_Type_name, int32(x))
}
func (x *Message_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Message_Type_value, data, "Message_Type")
	if err != nil {
		return err
	}
	*x = Message_Type(value)
	return nil
}

type Message struct {
	// Type Identifier
	Type             *Message_Type `protobuf:"varint,1,req,name=type,enum=delta.Message_Type" json:"type,omitempty"`
	Info             *string       `protobuf:"bytes,2,opt,name=info" json:"info,omitempty"`
	Point            *Point        `protobuf:"bytes,3,opt,name=point" json:"point,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}

func (m *Message) GetType() Message_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Message_ERROR
}

func (m *Message) GetInfo() string {
	if m != nil && m.Info != nil {
		return *m.Info
	}
	return ""
}

func (m *Message) GetPoint() *Point {
	if m != nil {
		return m.Point
	}
	return nil
}

type Point struct {
	X                *float64 `protobuf:"fixed64,1,req,name=x" json:"x,omitempty"`
	Y                *float64 `protobuf:"fixed64,2,req,name=y" json:"y,omitempty"`
	Z                *float64 `protobuf:"fixed64,3,req,name=z" json:"z,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Point) Reset()         { *m = Point{} }
func (m *Point) String() string { return proto.CompactTextString(m) }
func (*Point) ProtoMessage()    {}

func (m *Point) GetX() float64 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *Point) GetY() float64 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

func (m *Point) GetZ() float64 {
	if m != nil && m.Z != nil {
		return *m.Z
	}
	return 0
}

func init() {
	proto.RegisterEnum("delta.Message_Type", Message_Type_name, Message_Type_value)
}
